import uuid
import threading
import os
import time
from flask import Flask, request, jsonify
import subprocess
import requests
import base64 # For encoding images

# Initialize Flask app
app = Flask(__name__)

sessions = {}
sessions_lock = threading.Lock()

UPLOAD_FOLDER = 'uploads'
GENERATED_MERMAID_IMAGES_FOLDER = os.path.join(UPLOAD_FOLDER, 'mermaid_images')

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
if not os.path.exists(GENERATED_MERMAID_IMAGES_FOLDER):
    os.makedirs(GENERATED_MERMAID_IMAGES_FOLDER)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['GENERATED_MERMAID_IMAGES_FOLDER'] = GENERATED_MERMAID_IMAGES_FOLDER

MAX_ITERATIONS = 3 # Reduced for faster real API testing if it were live
OLLAMA_API_ENDPOINT = "http://localhost:11434/api/generate" # Standard Ollama endpoint
OLLAMA_MODEL_NAME = "qwen2.5vl:7b-q8_0" # User specified model
OLLAMA_REQUEST_TIMEOUT_INITIAL = 120 # seconds, initial generation might take longer
OLLAMA_REQUEST_TIMEOUT_COMPARISON = 180 # seconds, comparison with two images might take longer

# Sentinel string to check for in model's response for comparison
DIAGRAM_FINAL_SENTINEL = "DIAGRAM_IS_FINAL"

def encode_image_to_base64(image_path):
    """Encodes an image file to a base64 string."""
    try:
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')
    except Exception as e:
        app.logger.error(f"Error encoding image {image_path} to base64: {e}", exc_info=True)
        raise # Re-raise the exception to be handled by the caller

def call_vision_model_for_initial_diagram(image_path, text_context):
    """
    Calls the Ollama API with the QWEN model to generate an initial Mermaid diagram.
    """
    app.logger.info(f"OLLAMA_CALL: Initial diagram for {image_path} with context: '{text_context}' using model {OLLAMA_MODEL_NAME}")

    prompt = f"Describe the content of the provided image. "
    if text_context:
        prompt += f"Consider the following context: '{text_context}'. "
    prompt += "Based on this, generate a complete Mermaid syntax diagram that visually represents the image's structure or flow. Only output the Mermaid diagram text."

    try:
        base64_image = encode_image_to_base64(image_path)

        payload = {
            "model": OLLAMA_MODEL_NAME,
            "prompt": prompt,
            "images": [base64_image],
            "stream": False,
            "options": {"temperature": 0.3} # Adjust temperature for more deterministic output
        }

        app.logger.debug(f"OLLAMA_CALL: Initial diagram payload (omitting image data): {{'model': '{payload['model']}', 'prompt': '{payload['prompt']}', 'image_length': {len(base64_image)}}}")
        response = requests.post(OLLAMA_API_ENDPOINT, json=payload, timeout=OLLAMA_REQUEST_TIMEOUT_INITIAL)
        response.raise_for_status()

        model_output = response.json()
        current_mermaid_diagram = model_output.get("response", "").strip()

        if not current_mermaid_diagram:
            app.logger.warning("OLLAMA_CALL: Model returned an empty diagram for initial generation.")
            # Fallback to a very basic diagram if model returns nothing
            current_mermaid_diagram = f"graph TD;\n  A[Image: {os.path.basename(image_path)}];\n  B[No diagram generated by model];"
        else:
            # Clean up potential markdown code fences if model wraps output
            if current_mermaid_diagram.startswith("```mermaid"):
                current_mermaid_diagram = current_mermaid_diagram.split("```mermaid", 1)[1].strip()
            if current_mermaid_diagram.startswith("```"): # Generic code fence
                current_mermaid_diagram = current_mermaid_diagram.split("```",1)[1].strip()
            if current_mermaid_diagram.endswith("```"):
                current_mermaid_diagram = current_mermaid_diagram.rsplit("```", 1)[0].strip()

        app.logger.info(f"OLLAMA_CALL: Successfully received initial diagram (length {len(current_mermaid_diagram)}).")
        return current_mermaid_diagram

    except requests.exceptions.RequestException as e:
        app.logger.error(f"OLLAMA_CALL: API request failed for initial diagram: {e}", exc_info=True)
        return f"graph TD;\n  A[Error: Could not connect to Ollama model: {str(e)}];" # Return error as diagram
    except Exception as e: # Catches base64 encoding errors or other issues
        app.logger.error(f"OLLAMA_CALL: Failed to process initial diagram request: {e}", exc_info=True)
        return f"graph TD;\n  A[Error: Failed to process request for initial diagram: {str(e)}];"


def call_vision_model_for_comparison(original_image_path, generated_png_path, current_mermaid_diagram, iteration):
    """
    Calls the Ollama API with the QWEN model for comparison and refinement.
    The prompt asks the model to compare image1 (original) and image2 (generated from current_mermaid_diagram).
    """
    app.logger.info(f"OLLAMA_CALL: Comparing original '{original_image_path}' with generated PNG '{generated_png_path}' (Iteration {iteration}) using {OLLAMA_MODEL_NAME}")

    prompt = (
        f"You are an expert in analyzing diagrams. I have an original image ([image1]) and a second image ([image2]) "
        f"which was generated from the following Mermaid diagram:\n```mermaid\n{current_mermaid_diagram}\n```\n\n"
        f"Your task is to compare [image1] and [image2]. Identify key differences or missing elements in [image2] compared to [image1]. "
        f"Then, provide an updated Mermaid diagram that would make [image2] a more faithful representation of [image1]. "
        f"If you believe the current Mermaid diagram accurately represents the original image and no significant improvements can be made, "
        f"respond with the exact phrase '{DIAGRAM_FINAL_SENTINEL}' on a new line, followed by the current (unchanged) Mermaid diagram. "
        f"Otherwise, only output the new, updated Mermaid diagram text. Do not add any other commentary before or after the diagram or the sentinel phrase."
    )

    try:
        base64_original_image = encode_image_to_base64(original_image_path)
        base64_generated_png = encode_image_to_base64(generated_png_path)

        payload = {
            "model": OLLAMA_MODEL_NAME,
            "prompt": prompt,
            "images": [base64_original_image, base64_generated_png], # Order matters for the prompt
            "stream": False,
            "options": {"temperature": 0.2} # Lower temperature for more focused refinement
        }
        app.logger.debug(f"OLLAMA_CALL: Comparison payload (omitting image data): {{'model': '{payload['model']}', 'prompt': '{payload['prompt'][:100]}...', 'num_images': {len(payload['images'])}}}")

        response = requests.post(OLLAMA_API_ENDPOINT, json=payload, timeout=OLLAMA_REQUEST_TIMEOUT_COMPARISON)
        response.raise_for_status()

        model_output_text = response.json().get("response", "").strip()
        app.logger.debug(f"OLLAMA_CALL: Raw comparison response: '{model_output_text[:200]}...'")

        is_final = False
        updated_diagram = current_mermaid_diagram # Default to current if parsing fails or final

        if DIAGRAM_FINAL_SENTINEL in model_output_text:
            is_final = True
            # Extract the diagram part after the sentinel
            parts = model_output_text.split(DIAGRAM_FINAL_SENTINEL, 1)
            if len(parts) > 1:
                updated_diagram = parts[1].strip()
            else: # Sentinel found, but no diagram after it, keep current
                app.logger.warning("OLLAMA_CALL: Sentinel found but no diagram followed. Keeping current diagram.")
            # Further cleanup of diagram text if needed
            if updated_diagram.startswith("```mermaid"):
                updated_diagram = updated_diagram.split("```mermaid", 1)[1].strip()
            if updated_diagram.startswith("```"):
                updated_diagram = updated_diagram.split("```",1)[1].strip()
            if updated_diagram.endswith("```"):
                updated_diagram = updated_diagram.rsplit("```", 1)[0].strip()

            app.logger.info("OLLAMA_CALL: Model indicated diagram is final.")
        elif model_output_text: # If no sentinel, the whole response is treated as the new diagram
            updated_diagram = model_output_text
            # Clean up potential markdown code fences
            if updated_diagram.startswith("```mermaid"):
                updated_diagram = updated_diagram.split("```mermaid", 1)[1].strip()
            if updated_diagram.startswith("```"): # Generic code fence
                updated_diagram = updated_diagram.split("```",1)[1].strip()
            if updated_diagram.endswith("```"):
                updated_diagram = updated_diagram.rsplit("```", 1)[0].strip()
            app.logger.info(f"OLLAMA_CALL: Received updated diagram (length {len(updated_diagram)}).")
        else:
            app.logger.warning("OLLAMA_CALL: Model returned empty response for comparison. Keeping current diagram.")
            # is_final remains False, loop will continue or hit max iterations

        return {'is_final': is_final, 'updated_mermaid_diagram': updated_diagram, 'feedback': "Feedback from Ollama (processed)"}

    except requests.exceptions.RequestException as e:
        app.logger.error(f"OLLAMA_CALL: API request failed for comparison: {e}", exc_info=True)
        # Fallback: keep current diagram, don't consider final to allow retry or max iterations
        return {'is_final': False, 'updated_mermaid_diagram': current_mermaid_diagram, 'feedback': f"Error: Could not connect to Ollama for comparison: {str(e)}"}
    except Exception as e:
        app.logger.error(f"OLLAMA_CALL: Failed to process comparison request: {e}", exc_info=True)
        return {'is_final': False, 'updated_mermaid_diagram': current_mermaid_diagram, 'feedback': f"Error: Failed to process request for comparison: {str(e)}"}

def convert_mermaid_to_png(mermaid_text, session_id, iteration):
    """
    Converts Mermaid text to a PNG image using mmdc (mermaid-cli).
    Returns a path to the generated PNG.
    If conversion fails, it returns path to a dummy PNG with error info.
    """
    app.logger.info(f"MERMAID_CONVERSION: Starting for session {session_id}, Iteration {iteration}")
    base_filename = f"session_{session_id}_iter_{iteration}"
    temp_mermaid_file_path = os.path.join(app.config['GENERATED_MERMAID_IMAGES_FOLDER'], f"{base_filename}.mmd")
    generated_png_path = os.path.join(app.config['GENERATED_MERMAID_IMAGES_FOLDER'], f"{base_filename}.png")
    try:
        with open(temp_mermaid_file_path, 'w', encoding='utf-8') as f:
            f.write(mermaid_text)
        app.logger.debug(f"MERMAID_CONVERSION: Temporary Mermaid file created at {temp_mermaid_file_path}")
        mmdc_command = ['mmdc', '-i', temp_mermaid_file_path, '-o', generated_png_path, '-w', '1024', '-H', '768']
        app.logger.debug(f"MERMAID_CONVERSION: Executing command: {' '.join(mmdc_command)}")
        result = subprocess.run(mmdc_command, capture_output=True, text=True, timeout=30, check=False)
        if result.returncode != 0:
            error_message = (f"Mermaid to PNG conversion failed. Exit code: {result.returncode}.\n"
                             f"Stderr: {result.stderr.strip()}\nStdout: {result.stdout.strip()}")
            app.logger.error(f"MERMAID_CONVERSION: {error_message}")
            with open(generated_png_path, 'w', encoding='utf-8') as f_err:
                f_err.write(f"Error during mmdc conversion:\n{result.stderr.strip()}")
            return generated_png_path
        app.logger.info(f"MERMAID_CONVERSION: PNG image successfully created at {generated_png_path}")
        return generated_png_path
    except FileNotFoundError:
        msg = "`mmdc` command not found. Ensure @mermaid-js/mermaid-cli is installed globally and in PATH."
        app.logger.error(f"MERMAID_CONVERSION: {msg}")
        with open(generated_png_path, 'w', encoding='utf-8') as f_err: f_err.write(msg)
        return generated_png_path
    except subprocess.TimeoutExpired:
        msg = "`mmdc` command timed out after 30 seconds."
        app.logger.error(f"MERMAID_CONVERSION: {msg}")
        with open(generated_png_path, 'w', encoding='utf-8') as f_err: f_err.write(msg)
        return generated_png_path
    except Exception as e:
        msg = f"An unexpected error occurred during Mermaid to PNG conversion: {str(e)}"
        app.logger.error(msg, exc_info=True)
        with open(generated_png_path, 'w', encoding='utf-8') as f_err: f_err.write(msg)
        return generated_png_path
    finally:
        if os.path.exists(temp_mermaid_file_path):
            try:
                os.remove(temp_mermaid_file_path)
                app.logger.debug(f"MERMAID_CONVERSION: Cleaned up temporary file {temp_mermaid_file_path}")
            except Exception as e_clean:
                app.logger.error(f"MERMAID_CONVERSION: Error cleaning temporary file {temp_mermaid_file_path}: {e_clean}")

def process_image_to_diagram(session_id):
    app.logger.info(f"PROCESS_DIAGRAM: Starting for session {session_id}")
    with sessions_lock:
        session_data = sessions.get(session_id)
        if not session_data:
            app.logger.error(f"PROCESS_DIAGRAM: Session {session_id} not found.")
            return
        image_path = session_data['image_path']
        text_context = session_data['text_context']
    generated_png_path = None
    try:
        current_mermaid_diagram = call_vision_model_for_initial_diagram(image_path, text_context)
        app.logger.info(f"PROCESS_DIAGRAM: Session {session_id} - Initial diagram: '{current_mermaid_diagram[:100]}...'")
        for i in range(MAX_ITERATIONS):
            app.logger.info(f"PROCESS_DIAGRAM: Session {session_id} - Iteration {i+1}/{MAX_ITERATIONS}")
            if generated_png_path and os.path.exists(generated_png_path):
                try: os.remove(generated_png_path)
                except Exception as e_clean: app.logger.error(f"PROCESS_DIAGRAM: Error cleaning old PNG {generated_png_path}: {e_clean}")
            generated_png_path = convert_mermaid_to_png(current_mermaid_diagram, session_id, i)
            app.logger.info(f"PROCESS_DIAGRAM: Session {session_id} - New PNG path: {generated_png_path}")
            comparison_result = call_vision_model_for_comparison(image_path, generated_png_path, current_mermaid_diagram, i)
            current_mermaid_diagram = comparison_result['updated_mermaid_diagram']
            app.logger.info(f"PROCESS_DIAGRAM: Session {session_id} - Updated diagram: '{current_mermaid_diagram[:100]}...'")
            if comparison_result['is_final']:
                app.logger.info(f"PROCESS_DIAGRAM: Session {session_id} - Model indicated diagram is final.")
                break
        with sessions_lock:
            sessions[session_id]['diagram'] = current_mermaid_diagram
            sessions[session_id]['status'] = 'finished'
        app.logger.info(f"PROCESS_DIAGRAM: Session {session_id} - Finished successfully.")
    except Exception as e:
        app.logger.error(f"PROCESS_DIAGRAM: Session {session_id} - Error during processing: {e}", exc_info=True)
        with sessions_lock:
            sessions[session_id]['status'] = 'error'
            sessions[session_id]['error_message'] = str(e)
    finally:
        if generated_png_path and os.path.exists(generated_png_path):
            try: os.remove(generated_png_path)
            except Exception as cleanup_e: app.logger.error(f"PROCESS_DIAGRAM: Session {session_id} - Error cleaning final PNG: {cleanup_e}")

def generate_diagram_sync(session_id):
    app.logger.info(f"Starting synchronous generation for session: {session_id}")
    process_image_to_diagram(session_id)
    with sessions_lock:
        session = sessions[session_id]
        diagram = session.get('diagram')
        if session['status'] == 'error':
            raise Exception(session.get('error_message', 'Unknown error'))
    app.logger.info(f"Finished synchronous generation for session: {session_id}")
    return diagram

def generate_diagram_async(session_id):
    app.logger.info(f"Starting asynchronous generation for session: {session_id}")
    process_image_to_diagram(session_id)
    app.logger.info(f"Finished asynchronous generation for session: {session_id}")

@app.route('/image_to_diagram', methods=['POST'])
def image_to_diagram():
    app.logger.info("Received request for /image_to_diagram")
    if 'image_path' not in request.form:
        return jsonify({"error": "Missing 'image_path' in form data"}), 400
    image_path_relative = request.form['image_path']
    safe_image_path_relative = os.path.normpath(os.path.join('/', image_path_relative)).lstrip('/')
    image_path_full = os.path.join(app.config['UPLOAD_FOLDER'], safe_image_path_relative)
    if not os.path.abspath(image_path_full).startswith(os.path.abspath(app.config['UPLOAD_FOLDER'])):
        return jsonify({"error": "Invalid image path."}), 400
    if not os.path.exists(image_path_full):
        try:
            os.makedirs(os.path.dirname(image_path_full), exist_ok=True)
            with open(image_path_full, 'a'): pass
            app.logger.info(f"Created dummy file for testing: {image_path_full}")
        except Exception as e_create:
            return jsonify({"error": f"Image not found and dummy creation failed: {image_path_relative}"}), 404
    text_context = request.form.get('text_context', None)
    synchronous_str = request.form.get('synchronous', 'false').lower()
    synchronous = synchronous_str == 'true'
    session_id = str(uuid.uuid4())
    with sessions_lock:
        sessions[session_id] = {
            'status': 'in-progress', 'image_path': image_path_full, 'text_context': text_context,
            'diagram': None, 'error_message': None
        }
    app.logger.info(f"Created session: {session_id} for image: {image_path_relative}, sync: {synchronous}")
    if synchronous:
        try:
            diagram_text = generate_diagram_sync(session_id)
            return jsonify({"session_id": session_id, "diagram": diagram_text, "status": "finished"}), 200
        except Exception as e:
            error_message = str(e)
            with sessions_lock:
                if session_id in sessions and sessions[session_id]['status'] == 'error' and sessions[session_id]['error_message']:
                    error_message = sessions[session_id]['error_message']
            return jsonify({"session_id": session_id, "error": error_message, "status": "error"}), 500
    else:
        thread = threading.Thread(target=generate_diagram_async, args=(session_id,))
        thread.start()
        return jsonify({"session_id": session_id, "status": "in-progress"}), 202

@app.route('/status/<session_id>', methods=['GET'])
def get_status(session_id):
    with sessions_lock: session = sessions.get(session_id)
    if not session: return jsonify({"session_id": session_id, "status": "unknown"}), 404
    response = {"session_id": session_id, "status": session['status']}
    if session['status'] == 'finished': response['diagram'] = session.get('diagram')
    elif session['status'] == 'error': response['error_message'] = session.get('error_message')
    return jsonify(response), 200

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
